### ISSUE TITLE
i followed and got my music sequence generated but dont know how to make it to music to listen. 

### ISSUE THREAD

**Issue by nguyenvinh0604** [gauravtheP/Music-Generation-Using-Deep-Learning#2]
hi Gaurav Sharma and everyone,

thanks for this. im new to ML.

i followed and got my music sequence generated as below on Jupyter Notebook, but i dont know how to really turn these symbols to music to listen like what Sharma showed on Medium. can you help please advise more?

Thank you so much
best regards
V

M:6/8
K:Em
"Em"E2E G2B|"Em"BAG "Em"GAB|"A7"DEG E2G|
"Em"B2E G2A|"G"BAG BAG|"Am"ABc "G"dBG|"Am"FGA "E7"^GE^G|"Am"A3 -A2:|
P:B
B,|"Am"A,CE ABd|"Em"e^fe e2d|"Am"cBA "E7"BGE|"Am"AEA A3||

**Comment by SamSamhuns** [comment]
Clone this [https://github.com/leesavide/abcmidi](https://github.com/leesavide/abcmidi) repo and use the  Makefile to build the `abc2midi` executable. Then use a command like `./abc2midi gen.abc -o generated_music.midi` to get a playable midi file. 

However, the original author's abc notation metadata generator is very erroneous, and a lot of the metadata will usually be missing. Like in your example, the metadata value `X` and `W` are missing both of which are required by the `abc2midi` converter.

I personally used this script inside the last cell of the Jupyter Notebook to avoid this issue.
```python
ep = int(input("1. Which epoch number weight you want to load into the model(10, 20, 30, ..., 90). Small number will generate more errors in music: "))
ar = int(input("\n2. Enter any number between 0 to 86 which will be given as initial charcter to model for generating sequence: "))
ln = int(input("\n3. Enter the length of music sequence you want to generate. Typical number is between 300-600. Too small number will generate hardly generate any sequence: "))

music = generate_sequence(ep, ar, ln)

print("\nMUSIC SEQUENCE GENERATED: \n")

print(music)
with open('gen.abc', 'w') as abc:
    if music.find('W:') == -1:
        abc.write("W:Generated music\n")
    if music.find('X:') == -1:
        abc.write('X:1\n')
    if music.find('K:') == -1:
        abc.write('K:C\n')
    abc.write(music)
```
Now you can use `gen.abc` with the `abc2midi` converter.

**Comment by gauravtheP** [comment]
You have to copy-paste your music sequence here: https://abcjs.net/abcjs-editor.html
